version: "3.8"

services:
  db:
    image: postgres:13.3
    environment:
        - POSTGRES_USER=username
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=postclient_db
    ports:
        - "7777:5432"

  server:
    build: .
    depends_on:
        - db
    ports:
        - "8080:8080"

